### ISSUE TITLE
Improve handling of updating widgets for IS2Media's elpased time

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/InfoStats2#2]
The updating of widgets for the elapsed time still isn't right. The hook utilised doesn't seem to fire as expected, and instead is only called when an app starts playing media for the first time. 

It may be better to simply move to a small timer in IS2Media internally that will trigger needed callbacks every half-second or so when media is playing.

**Comment by ghost** [comment]
I wonder if the MPU you're hooking is updating time information. If not would a simple call to _startUpdatingTimeInformation work to fix this?

**Comment by Matchstic** [comment]
That's a good shout, potentially! Though, since I'm piggybacking off an existing instance of it I'd assume that would be called for me.

**Comment by Matchstic** [comment]
In theory this is now resolved with the last commit. Needs testing to double check.
