### ISSUE TITLE
Sunset time shows 24hr on a 12hr setting

### ISSUE THREAD

**Issue by jkauf55** [Matchstic/InfoStats2#4]
Like title states when using IS2 sunset time is 24hr when settings is set for 12hr[
![image](https://cloud.githubusercontent.com/assets/24393422/20894070/a7e4f8a8-bad9-11e6-9666-7026deb25c36.jpeg)
](url)

**Comment by Matchstic** [comment]
Fixed as of commit: https://github.com/Matchstic/InfoStats2/commit/1c9f5a912d13c4a86dbc96f33f765c11b41115f5

If you want to confirm your end too, please try this deb: https://www.dropbox.com/s/64zwegvk8pxbpmd/com.matchstic.InfoStats2_1.0.1-10_iphoneos-arm.deb?dl=0

**Comment by jkauf55** [comment]
Working correctly on my end Thanks!!!
